// ============================================================================
// Game DTOs - Data Transfer Objects for Game Service API
// ============================================================================
// Defines the request/response schemas for game-related HTTP endpoints.
// Uses my-class-validator decorators for JSON Schema generation.
//
// These DTOs are used by:
// - Matchmaking Service: Creates games after match confirmation
// - Admin endpoints: Manual game creation for testing
// ============================================================================

import { IsString, IsRequired, MinLength, generateSchema, IsEnum } from 'my-class-validator';

/**
 * DTO for creating a new game instance.
 *
 * This endpoint is called by the Matchmaking Service after both players
 * have confirmed their readiness in the ready-check phase.
 *
 * @example
 * POST /games
 * {
 *   "gameId": "match-abc123",
 *   "player1Id": "42",
 *   "player2Id": "43"
 * }
 */
export class CreateGameDto {
	/**
	 * Unique identifier for the game instance.
	 * Generated by the Matchmaking Service to track the match.
	 * Format: Usually "match-{uuid}" or "game-{timestamp}"
	 */
	@IsString({ message: 'gameId must be a string' })
	@IsRequired({ message: 'gameId is required' })
	@MinLength(1, { message: 'gameId cannot be empty' })
	gameId!: string;

	/**
	 * User ID of the first player.
	 * This is the numeric ID from the Auth Service (converted to string).
	 */
	@IsString({ message: 'player1Id must be a string' })
	@IsRequired({ message: 'player1Id is required' })
	@MinLength(1, { message: 'player1Id cannot be empty' })
	player1Id!: string;

	/**
	 * User ID of the second player.
	 * This is the numeric ID from the Auth Service (converted to string).
	 */
	@IsString({ message: 'player2Id must be a string' })
	@IsRequired({ message: 'player2Id is required' })
	@MinLength(1, { message: 'player2Id cannot be empty' })
	player2Id!: string;

	/**
	 * Type of the game.
	 * Determines the ruleset and context of the match.
	 */
	@IsString({ message: 'type must be a string' })
	@IsRequired({ message: 'type is required' })
	@IsEnum(['local', 'tournament', 'ranked', 'friend'], { message: 'Invalid game type' })
	type!: GameType;
}

export type GameType = 'local' | 'tournament' | 'ranked' | 'friend';

/**
 * Response DTO for successful game creation.
 * Returned with HTTP 201 Created status.
 */
export interface CreateGameResponseDto {
	/** Indicates the operation was successful */
	success: true;

	/** Unique identifier for the created game */
	gameId: string;

	/** Confirmation message */
	message: string;
}

/**
 * Response DTO for failed game creation.
 * Returned with HTTP 409 Conflict or other error status.
 */
export interface CreateGameErrorDto {
	/** Indicates the operation failed */
	success: false;

	/** Error code for programmatic handling */
	error: 'GAME_ALREADY_EXISTS' | 'PLAYER_ALREADY_IN_GAME' | 'INVALID_PLAYERS';

	/** Human-readable error message */
	message: string;
}

// Generate JSON Schema for request validation
export const CreateGameSchema = generateSchema(CreateGameDto);
