// ============================================================================
// Game Service Type Definitions
// ============================================================================
// Shared type definitions for the Game Service.
//
// This file contains:
// - JWT payload interface matching the Auth Service token structure
// - Socket type extensions for authenticated connections
// - Game-related type definitions
// ============================================================================

/**
 * JWT Payload interface matching the Auth Service token structure.
 *
 * This interface represents the decoded JWT token payload that is generated
 * by the Auth Service (apps/auth/src/auth/auth.service.ts). It is used
 * throughout the Game Service to identify and authenticate users.
 *
 * @remarks
 * - The `id` field is the primary user identifier
 * - The `id` is a number as generated by the Auth Service, but should be
 *   converted to string when used with internal services (e.g., GameService)
 * - The `@JWTBody` decorator from my-fastify-decorators automatically extracts
 *   and decodes this payload from the WebSocket handshake
 *
 * @see apps/auth/src/auth/auth.service.ts - Token generation (generateTokens method)
 */
export interface JwtPayload {
	/**
	 * Unique user identifier from the Auth Service database.
	 * This is the primary key used to identify users across all services.
	 */
	id: number;

	/**
	 * User's email address.
	 * May be empty string if user registered via OAuth without email.
	 */
	email: string;

	/**
	 * User's display name / username.
	 * Empty string if user hasn't set their username yet (see noUsername flag).
	 */
	username: string;

	/**
	 * Authentication provider used for login.
	 * Possible values: 'email', 'github', 'discord', '42', etc.
	 */
	provider: string;

	/**
	 * Flag indicating the user needs to set their username.
	 * When true, the frontend should prompt the user to choose a username.
	 */
	noUsername?: boolean;

	/**
	 * Suggested username from OAuth provider (e.g., GitHub login, Discord username).
	 * Only present when noUsername is true and user logged in via OAuth.
	 */
	suggestedUsername?: string;

	/**
	 * Token issued at timestamp (Unix epoch in seconds).
	 * Standard JWT claim, automatically set by @fastify/jwt.
	 */
	iat: number;

	/**
	 * Token expiration timestamp (Unix epoch in seconds).
	 * Standard JWT claim, automatically set by @fastify/jwt.
	 */
	exp: number;
}

/**
 * Error codes for game connection rejection.
 * These codes are sent to the client when a connection is rejected.
 */
export enum GameConnectionError {
	/** No valid JWT token was provided in the handshake */
	AUTH_REQUIRED = 'AUTH_REQUIRED',

	/** JWT token is present but invalid or expired */
	INVALID_TOKEN = 'INVALID_TOKEN',

	/** User ID extracted from JWT is invalid (not a positive number) */
	INVALID_USER_ID = 'INVALID_USER_ID',

	/** Player does not have a pending game created by Matchmaking Service */
	NO_PENDING_GAME = 'NO_PENDING_GAME',

	/** Player is trying to connect to a game they are not part of */
	UNAUTHORIZED_GAME_ACCESS = 'UNAUTHORIZED_GAME_ACCESS',
}

/**
 * Successful connection response sent to clients.
 */
export interface ConnectionSuccessResponse {
	status: 'connected';
	gameId: string;
	message: string;
}

/**
 * Error response sent to clients when connection fails.
 */
export interface ConnectionErrorResponse {
	code: GameConnectionError | string;
	message: string;
}
