### -----------------------
### SECTION LECTURE (GET)
### -----------------------

### Get stats player 1
GET http://localhost:3000/stats/user/1
Accept: application/json

### Get stats player 2
GET http://localhost:3000/stats/user/2
Accept: application/json

### Get player history
GET http://localhost:3000/match-history/user/1
Accept: application/json


### -----------------------
### SECTION ECRITURE (POST)
### -----------------------

### Register a match (Standard Ranked - No Tournament)
POST http://localhost:3000/match-history/add
Content-Type: application/json

{
    "game_id" : 1,
    "player1_id": 1,
    "player2_id": 2,
    "score_player1": 8,
    "score_player2": 5,
    "winner_id" : 1,
    "duration_seconds" : 500,
    "game_type" : "ranked",
    "tournament_id": -1,
    "is_final": false
}


### Register a match (Ranked - Player 2 Wins)
POST http://localhost:3000/match-history/add
Content-Type: application/json

{
    "game_id" : 4,
    "player1_id": 2,
    "player2_id": 3,
    "score_player1": 8,
    "score_player2": 5,
    "winner_id" : 2,
    "duration_seconds" : 500,
    "game_type" : "ranked",
    "tournament_id": -1,
    "is_final": false
}

### Register a match (Ranked - Revanche)
POST http://localhost:3000/match-history/add
Content-Type: application/json

{
    "game_id" : 1,
    "player1_id": 2,
    "player2_id": 1,
    "score_player1": 8,
    "score_player2": 5,
    "winner_id" : 2,
    "duration_seconds" : 500,
    "game_type" : "ranked"
}

### Register a match (Long Duration / High Score)
POST http://localhost:3000/match-history/add
Content-Type: application/json

{
    "game_id" : 13,
    "player1_id": 1,
    "player2_id": 2,
    "score_player1": 80,
    "score_player2": 5,
    "winner_id" : 2,
    "duration_seconds" : 3600,
    "game_type" : "ranked",
    "tournament_id": -1,
    "is_final": false
}

### Register a match (Tournament - Not Final)
POST http://localhost:3000/match-history/add
Content-Type: application/json

{
    "game_id" : 103,
    "player1_id": 1,
    "player2_id": 2,
    "score_player1": 11,
    "score_player2": 5,
    "winner_id" : 1,
    "duration_seconds" : 300,
    "game_type" : "tournament",
    "tournament_id": 900,
    "is_final": false
}

### Register a match (Tournament - FINAL)
POST http://localhost:3000/match-history/add
Content-Type: application/json

{
    "game_id": 60,
    "player1_id": 1,
    "player2_id": 2,
    "score_player1": 11,
    "score_player2": 9,
    "winner_id": 1,
    "duration_seconds": 300,
    "game_type": "tournament",
    "tournament_id": 900,
    "is_final": true
}

### Register a match false tournament
POST http://localhost:3000/match-history/add
Content-Type: application/json

{
    "game_id": 600,
    "player1_id": 1,
    "player2_id": 2,
    "score_player1": 11,
    "score_player2": 9,
    "winner_id": 1,
    "duration_seconds": 300,
    "game_type": "tournament",
    "tournament_id": 90,
    "is_final": true
}

### mumuse
POST http://localhost:3000/match-history/add
Content-Type: application/json

{
    "game_id": 345,
    "player1_id": 1,
    "player2_id": 2,
    "score_player1": 1,
    "score_player2": 9,
    "winner_id": 1,
    "duration_seconds": 300,
    "game_type": "ranked"

}
